### ISSUE TITLE
[issue] Minecraft 1.20.4 fabric loader, game crashed whilst initializing game. Caused by: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by StevenDean21st** [nanite/TheObsidianBoat#11]
Required dependency mod Trenzalore is installed.

Stack trace:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'obsidianboat'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/unrealdinnerbone/obsidianboat/client/ObsidianBoatRender
	at com.unrealdinnerbone.obsidianboat.ObsidianBoatFabricClient.onInitializeClient(ObsidianBoatFabricClient.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.unrealdinnerbone.obsidianboat.client.ObsidianBoatRender
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 8 more
```

**Comment by StevenDean21st** [comment]
Crash was fixed, close issue.
