### ISSUE TITLE
[Issue] Fabric 1.20.1, mod version 3.1.3 crashes upon initialization due to java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by modtraf** [nanite/TheObsidianBoat#14]
### Minecraft Version

1.20.1

### Modloader

fabric-loader-0.14.24-1.20.1

### Mod version

3.1.3

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-02-02 06:12:04
Description: Initializing game

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'obsidianboat'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/unrealdinnerbone/obsidianboat/client/ObsidianBoatRender
	at com.unrealdinnerbone.obsidianboat.ObsidianBoatFabricClient.onInitializeClient(ObsidianBoatFabricClient.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.unrealdinnerbone.obsidianboat.client.ObsidianBoatRender
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 8 more
---
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
```

### Steps to reproduce the issue

Launch modpack from curseforge app, hit play in the launcher, it will crash immediately upon trying to launch.

### Description of the issue you are having

For some reason the Curseforge app did not recognize this updated file as the most current version, so I downloaded it from the curseforge website and put it in my mod folder manually. I don't know if that helps. When I started it up it just crashed immediately.

This also looks like the error someone posted a few days ago that was fixed for the newest minecraft 1.20.4 version (https://github.com/nanite/TheObsidianBoat/issues/11) so... I'm hoping it doesn't consume a lot of your time to fix this. Thank you for compiling a version that'll work on 1.20.1, I'm super grateful :)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Fixed same as the other two
